version: '3.8'
services:
  todo-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: odo-app-production
    ports:
      - "8081:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped